[PEG-3578] added usage guide

diff --git a/.github/workflows/lint-openapi.yml b/.github/workflows/lint-openapi.yml
--- a/.github/workflows/lint-openapi.yml
+++ b/.github/workflows/lint-openapi.yml
@@ -20,7 +20,11 @@ jobs:
       - name: Find OpenAPI file
         id: find_spec
         run: |
-          FILE=$(find ${FILE_PATH_OPENAPI} -name "openapi-spec.yml" | head -n 1)
+          FILE=$(find ${FILE_PATH_OPENAPI} -name "*.openapi.yml" | head -n 1)
+          if [ -z "$FILE" ]; then
+            echo "❌ Error: no *.openapi.yml file found under ${FILE_PATH_OPENAPI}."
+            exit 1
+          fi
           echo "openapi_file=$FILE" >> $GITHUB_OUTPUT
 
       - name: Assert disallowed URLs are not present
